package com.blacklab.buddybounce.game

/**
 * How big each enemy actually is, world by world.
 *
 * The simulation has four enemy ROLES, but every world dresses those roles as its own creature -
 * forty pictures that used to share four boxes. A moth, a turret, a cherub and a jellyfish are
 * not the same size as each other, so one box for all of them was wrong forty ways at once: in
 * Heaven the rift's box was 92 wide on a creature 46 wide, so it killed from a clear head's
 * width of empty sky, and in Frozen Peaks the storm's was 62 tall on one 119 tall, so half of it
 * could be walked through.
 *
 * These numbers are MEASURED off the art, at 85% of the drawn body, by
 * tools/enemy/EnemyBoxCheck.kt. Under 1 on purpose and never over: a box that pokes out past the
 * picture kills the player with nothing on screen to blame, which is the one thing it must never
 * do, while a little slack inside the outline is invisible and always reads as fair. Faint ops
 * are left out of the measurement, so a glow, an aura or a trailing sparkle is scenery and not
 * lethal.
 *
 * Re-run that probe after touching EnemyArt: it checks these against the art and fails if a
 * creature has outgrown its box.
 */
object EnemyBox {

    private const val KINDS = 4

    // Half-width, half-height per role, in role order: bee, crow, storm, rift.
    // ROWS ARE IN FAUNA ORDER, which is not the order the worlds are listed in the menu -
    // Heaven's fauna is 5 while it is the last scene on the shelf.
    // Generated by tools/enemy/EnemyBoxCheck.kt.
    private val BOXES = floatArrayOf(
        49f, 49f, 68f, 54f, 68f, 78f, 98f, 98f,      // Backyard Skies  (fauna 0)
        59f, 53f, 105f, 99f, 54f, 82f, 98f, 98f,     // Deep Blue       (fauna 1)
        36f, 29f, 65f, 53f, 49f, 60f, 98f, 98f,      // Neon City       (fauna 2)
        54f, 53f, 53f, 58f, 68f, 101f, 98f, 98f,     // Frozen Peaks    (fauna 3)
        49f, 48f, 46f, 73f, 54f, 66f, 98f, 98f,      // Emberfall       (fauna 4)
        53f, 56f, 70f, 59f, 68f, 49f, 39f, 84f,      // Heaven          (fauna 5)
        60f, 37f, 88f, 39f, 53f, 74f, 98f, 98f,      // Dust Run        (fauna 6)
        71f, 36f, 82f, 60f, 57f, 63f, 91f, 63f,      // Overgrown       (fauna 7)
        42f, 40f, 53f, 46f, 71f, 71f, 98f, 98f,      // Sugar Rush      (fauna 8)
        34f, 26f, 61f, 39f, 60f, 70f, 98f, 98f       // Hollow Hill     (fauna 9)
    )

    /**
     * Row order must match render.Fauna's constants. They are not imported here: the simulation
     * does not depend on the renderer, and the scene's fauna is handed to [World] the same way
     * halo mode is.
     */
    const val ROWS = 10

    private fun at(fauna: Int, kind: Int, odd: Int): Float {
        val f = if (fauna in 0 until ROWS) fauna else 0
        val k = if (kind in 0 until KINDS) kind else 0
        return BOXES[f * KINDS * 2 + k * 2 + odd]
    }

    fun halfW(fauna: Int, kind: Int): Float = at(fauna, kind, 0)
    fun halfH(fauna: Int, kind: Int): Float = at(fauna, kind, 1)
}
