#!/usr/bin/env python3
"""Build world map data from a disassembly checkout.

The hardware renders a 160x144 window and nothing else, so a free camera has
to draw the world itself. Everything needed is in the disassembly as plain
binary files, which sidesteps the question of whether a given ROM stores its
room layouts compressed.

  rooms/<game>/small/roomXXXX.bin   10x8 metatile indices for one room
  rooms/<game>/large/roomXXXX.bin   16x11, used by dungeons and interiors
  rooms/<game>/groupNTilesets.bin   which tileset each room in a group uses
  tileset_layouts/<game>/
      tilesetMappingsNN.bin         256 metatiles, each four tiles of two
                                    bytes: tile index then attributes
      tilesetCollisionsNN.bin       one byte per metatile

A group is a 16x16 grid of rooms. Group 0 is the overworld.

Emits a C file holding the layouts and mappings, so the renderer needs no
files at run time.
"""

import argparse
import os
import sys

SMALL_W, SMALL_H = 10, 8
LARGE_W, LARGE_H = 16, 11
METATILE_PX = 16
GROUP_COLS = GROUP_ROWS = 16
ROOMS_PER_GROUP = GROUP_COLS * GROUP_ROWS


def load(path):
    with open(path, "rb") as fh:
        return fh.read()


def collect_group(disasm, game, group):
    """Room layouts for one group, in room order, plus the tileset each uses."""
    base = os.path.join(disasm, "rooms", game)
    layouts, missing = [], 0

    for room in range(ROOMS_PER_GROUP):
        index = group * 0x100 + room
        small = os.path.join(base, "small", f"room{index:04x}.bin")
        large = os.path.join(base, "large", f"room{index:04x}.bin")
        if os.path.exists(small):
            layouts.append(("small", load(small)))
        elif os.path.exists(large):
            layouts.append(("large", load(large)))
        else:
            layouts.append(("none", b""))
            missing += 1

    tileset_path = os.path.join(base, f"group{group}Tilesets.bin")
    tilesets = load(tileset_path) if os.path.exists(tileset_path) else bytes(256)
    return layouts, tilesets, missing


def collect_mappings(disasm, game):
    """Every tileset mapping present, indexed by its number."""
    base = os.path.join(disasm, "tileset_layouts", game)
    out = {}
    if not os.path.isdir(base):
        return out
    for name in sorted(os.listdir(base)):
        if not name.startswith("tilesetMappings") or not name.endswith(".bin"):
            continue
        stem = name[len("tilesetMappings"):-len(".bin")]
        if len(stem) != 2:
            continue                     # skip the Indices/Attributes variants
        try:
            out[int(stem, 16)] = load(os.path.join(base, name))
        except ValueError:
            continue
    return out


def emit_c(path, layouts, tilesets, mappings, group):
    lines = [
        "/* Generated by tools/worldmap.py - do not edit.",
        " *",
        " * Room layouts and tileset mappings for the world map renderer.",
        " * A group is a 16x16 grid of rooms; each small room is 10x8 metatiles",
        " * and each metatile is four 8x8 tiles, so the group covers",
        f" * {GROUP_COLS * SMALL_W * METATILE_PX}x{GROUP_ROWS * SMALL_H * METATILE_PX} pixels.",
        " */",
        '#include "worldmap.h"',
        "",
        f"const int gb_world_group = {group};",
        "",
        "/* Metatile indices, one room after another in room order. */",
        "const uint8_t gb_world_rooms[GB_WORLD_ROOMS][GB_ROOM_TILES] = {",
    ]

    for kind, data in layouts:
        cells = list(data[:SMALL_W * SMALL_H])
        cells += [0] * (SMALL_W * SMALL_H - len(cells))
        lines.append("    {" + ",".join(str(c) for c in cells) + "},")
    lines += ["};", ""]

    lines.append("/* Which tileset each room uses. */")
    lines.append("const uint8_t gb_world_room_tileset[GB_WORLD_ROOMS] = {")
    row = [str(tilesets[i] if i < len(tilesets) else 0) for i in range(ROOMS_PER_GROUP)]
    for i in range(0, len(row), 16):
        lines.append("    " + ",".join(row[i:i + 16]) + ",")
    lines += ["};", ""]

    top = max(mappings) + 1 if mappings else 1
    lines.append("/* Metatile definitions: four tiles of index and attributes. */")
    lines.append(f"const uint8_t gb_world_mappings[{top}][GB_MAPPING_BYTES] = {{")
    for i in range(top):
        data = mappings.get(i)
        if data is None:
            lines.append("    {0},")
            continue
        vals = list(data[:2048]) + [0] * max(0, 2048 - len(data))
        chunks = [",".join(str(v) for v in vals[j:j + 32]) for j in range(0, 2048, 32)]
        lines.append("    {" + ",\n     ".join(chunks) + "},")
    lines += ["};", "", f"const int gb_world_mapping_count = {top};", ""]

    with open(path, "w") as fh:
        fh.write("\n".join(lines))
    return len(lines)


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("disasm", help="path to the oracles-disasm checkout")
    ap.add_argument("--game", default="seasons", choices=["seasons", "ages"])
    ap.add_argument("--group", type=int, default=0,
                    help="0 is the overworld (default)")
    ap.add_argument("-o", "--out", default="build/world_data.c")
    args = ap.parse_args()

    if not os.path.isdir(os.path.join(args.disasm, "rooms")):
        raise SystemExit(f"error: {args.disasm} has no rooms/ directory")

    layouts, tilesets, missing = collect_group(args.disasm, args.game, args.group)
    mappings = collect_mappings(args.disasm, args.game)

    present = sum(1 for k, _ in layouts if k != "none")
    sizes = {}
    for kind, _ in layouts:
        sizes[kind] = sizes.get(kind, 0) + 1

    print(f"  group {args.group} ({args.game})")
    print(f"    rooms found     {present} of {ROOMS_PER_GROUP}"
          + (f", {missing} missing" if missing else ""))
    print(f"    room sizes      " + ", ".join(f"{k}: {v}" for k, v in sorted(sizes.items())))
    print(f"    tileset mappings {len(mappings)} loaded")
    print(f"    world extent    {GROUP_COLS * SMALL_W * METATILE_PX}"
          f"x{GROUP_ROWS * SMALL_H * METATILE_PX} px")

    os.makedirs(os.path.dirname(args.out) or ".", exist_ok=True)
    n = emit_c(args.out, layouts, tilesets, mappings, args.group)
    print(f"    wrote {args.out} ({n} lines)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
